<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework></PropertyGroup><ItemGroup><Compile Include="../../src/TechArrow.GameUpdater/Services/WindowsStartupService.cs" Link="WindowsStartupService.cs"/><Compile Include="../../src/TechArrow.GameUpdater/Services/AppUpdateService.cs" Link="AppUpdateService.cs"/><PackageReference Include="Velopack" Version="1.2.0"/></ItemGroup></Project>