using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using TechArrow.GameUpdater.Core.Models;
using TechArrow.GameUpdater.Infrastructure.Services;
var root = Path.Combine(Path.GetTempPath(), "TechArrowTests-" + Guid.NewGuid());
try
{
    var paths = new AppPaths(Path.Combine(root, "settings-data"));
    using var service = new SettingsService(paths, NullLogger<SettingsService>.Instance);
    var defaults = await service.LoadAsync(default);
    var migrationPaths = new AppPaths(Path.Combine(root, "timer-migration"));
    using var migrationService = new SettingsService(migrationPaths, NullLogger<SettingsService>.Instance);
    Directory.CreateDirectory(Path.GetDirectoryName(migrationPaths.SettingsFile)!);
    await File.WriteAllTextAsync(migrationPaths.SettingsFile, "{\"IdleSeconds\":60,\"OtherLauncherIdleSeconds\":300,\"GraceSeconds\":90,\"SteamPath\":\"D:\\\\Steam\\\\steam.exe\"}");
    var migratedTimers = await migrationService.LoadAsync(default);
    Check(migratedTimers.IdleSeconds == 120 && migratedTimers.OtherLauncherIdleSeconds == 120 && migratedTimers.GraceSeconds == 0 && migratedTimers.SteamPath!.Contains("Steam"), "old standard timers migrate without losing launcher path");
    await File.WriteAllTextAsync(migrationPaths.SettingsFile, "{\"IdleSeconds\":60,\"OtherLauncherIdleSeconds\":600,\"GraceSeconds\":90}");
    Check((await migrationService.LoadAsync(default)).OtherLauncherIdleSeconds == 600 && (await migrationService.LoadAsync(default)).GraceSeconds == 90, "custom legacy timers remain unchanged");
    var activityTime = DateTimeOffset.UtcNow;
    var idlePolicy = new LauncherIdlePolicy(activityTime, 60, 30);
    LauncherActivitySample Quiet(int seconds, string identity = "10:100") => new(activityTime.AddSeconds(seconds), true, true, false, true, identity, 0, 0, "");
    Check(!idlePolicy.Evaluate(Quiet(0)).ReadyToClose, "other client startup warmup does not close launcher");
    idlePolicy.Evaluate(Quiet(120));
    Check(!idlePolicy.Evaluate(Quiet(180)).ReadyToClose && idlePolicy.Evaluate(Quiet(210)).ReadyToClose, "other client requires full sustained idle plus grace after startup warmup");
    Check(!idlePolicy.Evaluate(Quiet(211) with { IoBytesPerSecond = 12000 }).ReadyToClose, "file or network I/O cancels pending close");
    idlePolicy.Evaluate(Quiet(220));
    Check(!idlePolicy.Evaluate(Quiet(310) with { CpuSecondsPerSecond = 0.5 }).ReadyToClose, "installation CPU activity blocks close even when disk is quiet");
    idlePolicy.Evaluate(Quiet(320));
    Check(!idlePolicy.Evaluate(Quiet(410) with { BusyWithGameOrUser = true }).ReadyToClose, "game or user activity prevents close");
    idlePolicy.Evaluate(Quiet(420));
    Check(!idlePolicy.Evaluate(Quiet(510) with { Reliable = false }).ReadyToClose, "unreadable process counters block close");
    idlePolicy.Evaluate(Quiet(520));
    Check(!idlePolicy.Evaluate(Quiet(610, "10:200")).ReadyToClose, "replaced process identity resets idle countdown");
    Check(!idlePolicy.Evaluate(Quiet(620) with { HasMeasurement = false }).ReadyToClose, "initial counters cannot establish idle");
    Check(!idlePolicy.Evaluate(Quiet(630) with { IoBytesPerSecond = double.NaN }).ReadyToClose, "invalid counters block close");
    Check(idlePolicy.Evaluate(Quiet(640) with { IsRunning = false, Reliable = false }).State != "Клиент закрыт", "unreadable process is not reported as exited");
    var quickPolicy = new LauncherIdlePolicy(activityTime, 120, 0, countStartupIdle: true);
    quickPolicy.Evaluate(Quiet(0)); quickPolicy.Evaluate(Quiet(1));
    Check(!quickPolicy.Evaluate(Quiet(120)).ReadyToClose && quickPolicy.Evaluate(Quiet(121)).ReadyToClose, "two-minute idle overlaps startup check");
    Check(!quickPolicy.Evaluate(Quiet(122) with { IoBytesPerSecond = 12000 }).ReadyToClose, "activity resets two-minute timer");
    quickPolicy.Evaluate(Quiet(123));
    Check(!quickPolicy.Evaluate(Quiet(242)).ReadyToClose && quickPolicy.Evaluate(Quiet(243)).ReadyToClose, "reset requires another full two-minute idle");
    var separatePolicy = new LauncherIdlePolicy(activityTime, 60, 30, 1, 0.01, true);
    LauncherActivitySample Separate(int seconds) => Quiet(seconds) with { HasSeparateMeasurement = true };
    separatePolicy.Evaluate(Separate(120)); separatePolicy.Evaluate(Separate(121));
    Check(!separatePolicy.Evaluate(Separate(210) with {NetworkBytesPerSecond=2048}).ReadyToClose, "network transfer prevents exit while disk is quiet");
    separatePolicy.Evaluate(Separate(220));
    Check(!separatePolicy.Evaluate(Separate(310) with {DiskBytesPerSecond=65536}).ReadyToClose, "disk installation prevents exit after network stops");
    separatePolicy.Evaluate(Separate(320));
    Check(!separatePolicy.Evaluate(Separate(410) with {HasSeparateMeasurement=false}).ReadyToClose, "missing separate measurements reset countdown");
    separatePolicy.Evaluate(Separate(420));
    Check(!separatePolicy.Evaluate(Separate(510) with {NetworkBytesPerSecond=double.NaN}).ReadyToClose, "invalid network rate cannot establish idle");
    separatePolicy.Evaluate(Separate(520));
    Check(separatePolicy.Evaluate(Separate(610)).ReadyToClose, "both network and disk quiet for full idle plus grace allow exit");
    Check(!separatePolicy.Evaluate(Separate(611) with {IoBytesPerSecond=65536}).ReadyToClose, "cached file I/O remains a conservative guard");
    Check(Enumerable.Range(1,7).All(i => LauncherProcessProfile.For(i).Frontends.Length > 0 && LauncherProcessProfile.For(i).TrayNames.Length > 0), "all seven launchers have explicit process and tray profiles");
    Check(!LauncherProcessProfile.Within(Path.Combine(root,"launcher-other","fake.exe"),Path.Combine(root,"launcher")), "similarly named directory is not a trusted launcher directory");
    Check(defaults.AutoCloseOtherLaunchers && defaults.OtherLauncherIdleSeconds == 120, "other clients default to enabled close with two-minute idle");
    using var otherSettings = new SettingsService(new AppPaths(Path.Combine(root,"other-settings")), NullLogger<SettingsService>.Instance);
    await otherSettings.SaveAsync(defaults with { AutoCloseOtherLaunchers = false, OtherLauncherIdleSeconds = 600 }, default);
    Check(!(await otherSettings.LoadAsync(default)).AutoCloseOtherLaunchers && (await otherSettings.LoadAsync(default)).OtherLauncherIdleSeconds == 600, "other launcher settings survive persistence");
    foreach (var invalidIdle in new[] { 0, 59, 86401 }) await Throws<InvalidDataException>(() => Task.Run(() => (defaults with {OtherLauncherIdleSeconds=invalidIdle}).Validate()));
    var historyPaths = new AppPaths(Path.Combine(root, "history-data"));
    var history = new RunHistoryService(historyPaths);
    var recordedRun = history.Begin("Обновить всё");
    history.Add(recordedRun, "Epic: запуск отправлен; завершение неизвестно.");
    history.Finish(recordedRun, "Завершено с ошибками");
    var loadedHistory = new RunHistoryService(historyPaths);
    Check(loadedHistory.Snapshot[0].Id == recordedRun && loadedHistory.Snapshot[0].Details.Count == 1 && loadedHistory.Snapshot[0].Result == "Завершено с ошибками", "history persists run identity, results and details across restart");
    loadedHistory.Begin("По расписанию");
    Check(new RunHistoryService(historyPaths).Snapshot[0].Result.StartsWith("Прервано"), "unfinished session is interrupted rather than successful after restart");
    var historyFile = Path.Combine(historyPaths.Root, "History", "runs.json");
    await File.WriteAllTextAsync(historyFile, "{broken");
    await Throws<System.Text.Json.JsonException>(() => Task.Run(() => new RunHistoryService(historyPaths)));
    Check(await File.ReadAllTextAsync(historyFile) == "{broken", "corrupt history remains untouched");
    var notificationPolicy = new ErrorNotificationPolicy();
    var notificationTime = DateTimeOffset.UtcNow;
    Check(notificationPolicy.ShouldNotify(notificationTime) && !notificationPolicy.ShouldNotify(notificationTime.AddSeconds(5)) && notificationPolicy.ShouldNotify(notificationTime.AddMinutes(1)), "error notifications are throttled for one minute");
    Check(ClubEndpointPolicy.Validate("https://clubs.example.com").AbsoluteUri == "https://clubs.example.com/", "HTTPS club endpoint accepted");
    Check(ClubEndpointPolicy.Validate("http://localhost:5080").IsLoopback, "local HTTP club test accepted");
    foreach (var invalidEndpoint in new[] { "http://example.com", "https://user:password@example.com", "file:///tmp/data", "https://example.com?key=secret" })
        await Throws<InvalidDataException>(() => Task.Run(() => ClubEndpointPolicy.Validate(invalidEndpoint)));
    var launcherFixture = Path.Combine(root, "launcher-fixture");
    Directory.CreateDirectory(launcherFixture);
    var testExecutable = Path.Combine(launcherFixture, "client.exe");
    await File.WriteAllTextAsync(testExecutable, "test fixture, never executed");
    var launcherRequests = LauncherStartupService.Requests(defaults with { EpicPath = testExecutable, LestaPath = "Lesta", BattleNetPath = "BattleNet", EaPath = "EA", RiotPath = "Riot", VkPlayPath = "VK", WargamingPath = "WG" });
    Check(launcherRequests.Count == 7 && launcherRequests.Select(item => item.CardIndex).SequenceEqual(Enumerable.Range(1, 7)) && launcherRequests.Select(item => item.Executable).SequenceEqual(new[] { testExecutable, "Lesta", "BattleNet", "EA", "Riot", "VK", "WG" }), "all seven other launcher settings map to their own cards");
    var requestedStarts = new List<string>();
    var sent = LauncherStartupService.Start(launcherRequests[0], default, requestedStarts.Add, _ => false);
    Check(requestedStarts.SequenceEqual(new[] { testExecutable }) && sent.Status == "Запрос запуска отправлен", "configured client receives one launch request without claiming download completion");
    LauncherStartupService.Start(launcherRequests[0], default, requestedStarts.Add, _ => true);
    Check(requestedStarts.Count == 1, "running client is not launched twice");
    Check(LauncherStartupService.Start(new(1, "Epic Games", null), default, requestedStarts.Add, _ => false).Status == "Путь не выбран", "unconfigured client gives actionable status");
    await Throws<FileNotFoundException>(() => Task.Run(() => LauncherStartupService.Start(new(1, "Epic Games", Path.Combine(launcherFixture, "missing.exe")), default, requestedStarts.Add, _ => false)));
    using var startCancellation = new CancellationTokenSource(); startCancellation.Cancel();
    await Throws<OperationCanceledException>(() => Task.Run(() => LauncherStartupService.Start(launcherRequests[0], startCancellation.Token, requestedStarts.Add, _ => false)));
    Check(requestedStarts.Count == 1, "cancelled startup makes no launch request");
    var scheduledManifest = "\"AppState\"\n{\n\t\"appid\" \"3527290\"\n\t\"name\" \"PEAK\"\n\t\"StateFlags\" \"6\"\n\t\"AutoUpdateBehavior\" \"0\"\n\t\"ScheduledAutoUpdate\" \"1792366519\"\n\t\"InstalledDepots\" { \"3527291\" { \"manifest\" \"506013008200123818\" } }\n}";
    var preparedManifest = SteamScheduledUpdatePreparation.PrepareCandidate(scheduledManifest);
    Check(preparedManifest == scheduledManifest.Replace("\"AutoUpdateBehavior\" \"0\"", "\"AutoUpdateBehavior\" \"2\"").Replace("\"ScheduledAutoUpdate\" \"1792366519\"", "\"ScheduledAutoUpdate\" \"0\""), "offline candidate changes only scheduling and priority");
    var queueLibrary = Path.Combine(root, "queue-library");
    var secondQueueLibrary = Path.Combine(root, "second-queue-library");
    Directory.CreateDirectory(Path.Combine(queueLibrary, "steamapps"));
    Directory.CreateDirectory(Path.Combine(secondQueueLibrary, "steamapps"));
    var peakManifestPath = Path.Combine(queueLibrary, "steamapps", "appmanifest_3527290.acf");
    var redistributablesPath = Path.Combine(secondQueueLibrary, "steamapps", "appmanifest_228980.acf");
    var redistributablesManifest = scheduledManifest.Replace("3527290", "228980").Replace("PEAK", "Steamworks Common Redistributables");
    await File.WriteAllTextAsync(peakManifestPath, scheduledManifest);
    await File.WriteAllTextAsync(redistributablesPath, redistributablesManifest);
    var queueBackups = Path.Combine(root, "queue-backups");
    await Throws<InvalidOperationException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareLibraries([queueLibrary], queueBackups, default, () => true)));
    Check(await File.ReadAllTextAsync(peakManifestPath) == scheduledManifest && !Directory.Exists(queueBackups), "running Steam prevents writes and backups");
    var queueResult = SteamScheduledUpdatePreparation.PrepareLibraries([queueLibrary, secondQueueLibrary, queueLibrary], queueBackups, default, () => false);
    Check(queueResult.Prepared.Count == 2 && queueResult.Warnings.Count == 0, "all libraries include Steamworks packages and duplicate libraries are ignored");
    Check(await File.ReadAllTextAsync(peakManifestPath) == preparedManifest, "pending game receives immediate update settings");
    Check((await File.ReadAllTextAsync(redistributablesPath)).Contains("\"ScheduledAutoUpdate\" \"0\""), "Steamworks package delay is cleared");
    var originals = Directory.GetFiles(queueBackups, "*.acf", SearchOption.AllDirectories);
    Check(originals.Length == 2 && originals.Any(path => File.ReadAllText(path) == scheduledManifest) && originals.Any(path => File.ReadAllText(path) == redistributablesManifest), "exact original manifests are backed up outside Steam");
    Check(SteamScheduledUpdatePreparation.PrepareLibraries([queueLibrary, secondQueueLibrary], queueBackups, default, () => false).Prepared.Count == 0, "prepared updates are not rewritten repeatedly");
    await File.WriteAllTextAsync(peakManifestPath, scheduledManifest);
    var offlineChecks = 0;
    await Throws<InvalidOperationException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareLibraries([queueLibrary], queueBackups, default, () => ++offlineChecks >= 3)));
    Check(await File.ReadAllTextAsync(peakManifestPath) == scheduledManifest, "Steam starting before commit prevents manifest replacement");
    Check(Directory.GetFiles(Path.Combine(queueLibrary, "steamapps"), "*.tmp").Length == 0, "aborted preparation removes its temporary file");
    using var queueCancellation = new CancellationTokenSource(); queueCancellation.Cancel();
    await Throws<OperationCanceledException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareLibraries([queueLibrary], queueBackups, queueCancellation.Token, () => false)));
    await Throws<InvalidDataException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareCandidate(scheduledManifest.Replace("\"StateFlags\" \"6\"", "\"StateFlags\" \"4\""))));
    await Throws<InvalidDataException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareCandidate(scheduledManifest.Replace("\"StateFlags\" \"6\"", "\"StateFlags\" \"1048582\""))));
    await Throws<InvalidDataException>(() => Task.Run(() => SteamScheduledUpdatePreparation.PrepareCandidate(scheduledManifest.Replace("\"AutoUpdateBehavior\" \"0\"", "\"AutoUpdateBehavior\" \"0\"\n\t\"AutoUpdateBehavior\" \"1\""))));
    Check(defaults.GraceSeconds == 0 && defaults.IdleSeconds == 120 && !defaults.AllowForceClose && !defaults.ParallelUpdates, "safe defaults");
    Check(!Directory.Exists(paths.Root), "load missing configuration is read-only");
    Directory.CreateDirectory(Path.GetDirectoryName(paths.SettingsFile)!);
    await File.WriteAllTextAsync(paths.SettingsFile, "{\"SchemaVersion\":1,\"SteamPath\":\"legacy-steam.exe\"}");
    var legacy = await service.LoadAsync(default);
    Check(legacy.SteamPath == "legacy-steam.exe" && legacy.BattleNetPath is null && legacy.WargamingPath is null, "legacy settings remain compatible");
    var custom = defaults with { SteamPath = @"D:\Игры\Steam\steam.exe", GraceSeconds = 101, BattleNetPath = @"C:\Games\BattleNet\client.exe", EaPath = @"C:\Games\Ea\client.exe", RiotPath = @"C:\Games\Riot\client.exe", VkPlayPath = @"C:\Games\VkPlay\client.exe", WargamingPath = @"C:\Games\Wargaming\client.exe" };
    await service.SaveAsync(custom, default);
    Check(await service.LoadAsync(default) == custom, "JSON round-trip");
    await Throws<InvalidDataException>(() => service.SaveAsync(custom with { IdleSeconds = 0 }, default));
    Check(await service.LoadAsync(default) == custom, "invalid save preserves configuration");
    await Task.WhenAll(Enumerable.Range(1, 12).Select(i => service.SaveAsync(custom with { GraceSeconds = i }, default)));
    Check((await service.LoadAsync(default)).GraceSeconds > 0, "concurrent writes produce valid JSON");
    var bytes = await File.ReadAllTextAsync(paths.SettingsFile);
    using var cancelled = new CancellationTokenSource(); cancelled.Cancel();
    await Throws<OperationCanceledException>(() => service.SaveAsync(custom, cancelled.Token));
    Check(await File.ReadAllTextAsync(paths.SettingsFile) == bytes, "cancellation preserves file");
    await File.WriteAllTextAsync(paths.SettingsFile, "{broken");
    await Throws<System.Text.Json.JsonException>(() => service.LoadAsync(default));
    Check(await File.ReadAllTextAsync(paths.SettingsFile) == "{broken", "corrupt configuration is not replaced");
    await using (var logs = new LoggingService(paths))
    {
        logs.CreateLogger("Smoke").LogInformation("Real logging test");
        Check(logs.Snapshot.Count == 1, "live log buffer");
    }
    Check((await File.ReadAllTextAsync(Directory.GetFiles(paths.LogsDirectory).Single())).Contains("Real logging test"), "logs flush on shutdown");
    var steamRoot = Path.Combine(root, "Steam");
    var secondLibrary = Path.Combine(root, "Second Library");
    Directory.CreateDirectory(Path.Combine(steamRoot, "steamapps", "common", "Test Game"));
    Directory.CreateDirectory(Path.Combine(secondLibrary, "steamapps", "common", "Second Game"));
    await File.WriteAllTextAsync(Path.Combine(steamRoot, "steam.exe"), "fixture, never executed");
    var escapedLibrary = secondLibrary.Replace("\\", "\\\\");
    await File.WriteAllTextAsync(Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf"),
        "\"libraryfolders\" { \"1\" { \"path\" \"" + escapedLibrary + "\" } }");
    await File.WriteAllTextAsync(Path.Combine(steamRoot, "steamapps", "appmanifest_10.acf"),
        "\"AppState\" { \"appid\" \"10\" \"name\" \"Тестовая игра\" \"installdir\" \"Test Game\" }");
    await File.WriteAllTextAsync(Path.Combine(secondLibrary, "steamapps", "appmanifest_20.acf"),
        "// comment\n\"AppState\" { \"appid\" \"20\" \"name\" \"Second Game\" \"installdir\" \"Second Game\" }");
    await File.WriteAllTextAsync(Path.Combine(secondLibrary, "steamapps", "appmanifest_30.acf"), "\"AppState\" {");
    var steamService = new SteamService();
    var inventory = steamService.Scan(steamRoot);
    Check(inventory.ExecutablePath == Path.Combine(steamRoot, "steam.exe"), "Steam configured directory detection");
    Check(inventory.Libraries.Count == 2 && inventory.Games.Count == 2, "Steam multiple libraries and installed games");
    Check(inventory.Games.Any(g => g.Name == "Тестовая игра"), "Steam Unicode game names");
    Check(inventory.Warnings.Count == 1, "Steam corrupt manifest does not hide valid games");
    var missing = steamService.Scan(Path.Combine(root, "Missing", "steam.exe"));
    Check(missing.ExecutablePath is null && missing.Games.Count == 0 && missing.Warnings.Count > 0, "Steam invalid configured path is reported");
    await File.WriteAllTextAsync(Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf"),
        "\"LibraryFolders\" { \"1\" \"" + escapedLibrary + "\" }");
    Check(steamService.Scan(steamRoot).Games.Count == 2, "Steam legacy library format");
    await File.WriteAllTextAsync(Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf"), "\"libraryfolders\" {");
    var partial = steamService.Scan(steamRoot);
    Check(partial.Games.Count == 1 && partial.Warnings.Count > 0, "Steam malformed library list preserves main library");
    var actual = steamService.Scan(null);
    Console.WriteLine($"Local Steam detection: {actual.ExecutablePath ?? "not found"}, games: {actual.Games.Count}");
    var now = DateTimeOffset.UtcNow;
    var pendingUpdate = new SteamUpdate("10", "Test", 1026, 100, 50, 100, 0);
    var installedUpdate = pendingUpdate with { Flags = 4, DownloadedBytes = 100, StagedBytes = 100 };
    SteamMonitorSample Sample(int seconds, string fingerprint, SteamUpdate update, bool reliable = true, bool? gameRunning = false)
        => new(now.AddSeconds(seconds), true, reliable, gameRunning, fingerprint, [update]);
    var emptyQueuePolicy = new SteamCompletionPolicy(10, 5, 1, allowNoUpdates: true);
    var idleInstall = installedUpdate with { TotalBytes = null, DownloadedBytes = null, StageBytes = null, StagedBytes = null };
    Check(!emptyQueuePolicy.Evaluate(Sample(0, "idle", idleInstall)).ReadyToClose, "maintenance without updates still waits for idle");
    Check(!emptyQueuePolicy.Evaluate(Sample(14, "idle", idleInstall)).ReadyToClose, "maintenance without updates waits for grace");
    Check(emptyQueuePolicy.Evaluate(Sample(15, "idle", idleInstall)).ReadyToClose, "maintenance without updates can finish with installed manifests");
    Check(!emptyQueuePolicy.Evaluate(Sample(16, "idle", idleInstall, gameRunning: true)).ReadyToClose, "game blocks no-update maintenance exit");
    Check(!emptyQueuePolicy.Evaluate(Sample(17, "idle", idleInstall, reliable: false)).ReadyToClose, "unreliable data blocks no-update maintenance exit");
    Check(!emptyQueuePolicy.Evaluate(new(now.AddSeconds(18), true, true, false, "idle", [])).ReadyToClose, "empty manifest inventory cannot prove no updates");
    Check(!emptyQueuePolicy.Evaluate(Sample(19, "pending", pendingUpdate)).ReadyToClose, "new download blocks no-update maintenance exit");
    Check(!emptyQueuePolicy.Evaluate(Sample(40, "idle", idleInstall)).ReadyToClose, "observed download still needs installation counters");
    var policy = new SteamCompletionPolicy(10, 5, 1);
    Check(!policy.Evaluate(Sample(0, "initial", installedUpdate)).ReadyToClose, "idle client cannot prove observed completion");
    Check(!policy.Evaluate(Sample(1, "download", pendingUpdate)).ReadyToClose, "active download blocks exit");
    Check(!policy.Evaluate(Sample(70, "download", pendingUpdate)).ReadyToClose, "stalled download blocks exit");
    Check(policy.Evaluate(Sample(71, "download", pendingUpdate)).State.Contains("зависло"), "stalled download is reported");
    Check(!policy.Evaluate(Sample(72, "installed", installedUpdate)).ReadyToClose, "completion starts idle window");
    Check(policy.Evaluate(Sample(82, "installed", installedUpdate)).State == "Пауза перед закрытием", "idle then grace window");
    Check(policy.Evaluate(Sample(87, "installed", installedUpdate)).ReadyToClose, "observed completion plus idle and grace permits exit");
    Check(!policy.Evaluate(Sample(88, "new activity", installedUpdate)).ReadyToClose, "new file activity resets exit countdown");
    Check(!policy.Evaluate(Sample(200, "new activity", installedUpdate, false)).ReadyToClose, "read failures block exit");
    Check(!policy.Evaluate(Sample(300, "new activity", installedUpdate)).ReadyToClose, "recovery restarts full countdown");
    Check(!policy.Evaluate(Sample(400, "new activity", installedUpdate, gameRunning: true)).ReadyToClose, "running game blocks exit");
    Check(!policy.Evaluate(Sample(500, "new activity", installedUpdate, gameRunning: null)).ReadyToClose, "unknown running games blocks exit");
    Check(!policy.Evaluate(new(now.AddSeconds(600), true, true, false, "gone", [])).ReadyToClose, "disappeared observed manifest blocks exit");
    Check(!policy.Evaluate(Sample(700, "installing", installedUpdate with { Flags = 131076, StagedBytes = 50 })).ReadyToClose, "download 100 percent is not completed installation");
    Check(!policy.Evaluate(Sample(800, "unknown", installedUpdate with { StageBytes = null, StagedBytes = null })).ReadyToClose, "unknown install counters block exit");
    Check(pendingUpdate.DownloadPercent == 50, "download percentage uses recorded byte counts");
    using (var reader = new SteamMonitorReader(Path.Combine(steamRoot, "steam.exe")))
        Check(!reader.Read().Sample.Reliable, "missing content log and malformed manifests block automatic exit");
    Check(!(pendingUpdate with { Flags = 64, TotalBytes = 0, DownloadedBytes = 0, StageBytes = 0, StagedBytes = 0 }).Pending, "running game alone does not count as observed update");
    Check((pendingUpdate with { Flags = 514 }).Phase == "пауза", "paused download is labeled accurately");
    await Throws<OperationCanceledException>(() => SteamMonitorReader.RequestExitAsync(Path.Combine(steamRoot, "steam.exe"), 1, cancelled.Token));
    var weekly = defaults with { ScheduleEnabled = true, ScheduleTime = "04:00", ScheduleDays = 1 << (int)DayOfWeek.Wednesday, ScheduleAutoCloseSteam = true };
    var occurrence = new DateTimeOffset(2026, 10, 7, 4, 0, 0, TimeSpan.FromHours(5));
    Check(WeeklySchedule.Next(weekly, occurrence.AddSeconds(-1)) == occurrence, "schedule finds next selected weekday in Qyzylorda timezone");
    Check(WeeklySchedule.Next(weekly, occurrence) == occurrence.AddDays(7), "schedule rolls over one full week after due time");
    Check(WeeklySchedule.Due(weekly, occurrence.ToUniversalTime()) == occurrence, "schedule due time is independent of PC timezone");
    Check(WeeklySchedule.Due(weekly, occurrence.AddSeconds(59)) == occurrence, "schedule tolerates timer delay within due minute");
    Check(WeeklySchedule.Due(weekly, occurrence.AddMinutes(1)) is null, "schedule does not launch missed runs later");
    Check(WeeklySchedule.Due(weekly, occurrence.AddDays(-1)) is null, "unselected weekday is skipped");
    Check(WeeklySchedule.Next(weekly with { ScheduleEnabled = false }, occurrence) is null, "disabled schedule has no next run");
    await Throws<InvalidDataException>(() => service.SaveAsync(weekly with { ScheduleDays = 0 }, default));
    await Throws<InvalidDataException>(() => service.SaveAsync(weekly with { ScheduleTime = "25:00" }, default));
    await service.SaveAsync(weekly, default);
    Check(await service.LoadAsync(default) == weekly, "schedule options persist across settings reload");
    var stateStore = new ScheduleStateStore(paths);
    Check(stateStore.TryClaim(occurrence), "schedule reserves new occurrence before launching");
    Check(!new ScheduleStateStore(paths).TryClaim(occurrence), "schedule duplicate is blocked after application restart");
    Check(!stateStore.TryClaim(occurrence.AddDays(-7)), "clock rollback cannot repeat old occurrence");
    Check(stateStore.TryClaim(occurrence.AddDays(7)), "next weekly occurrence can run");
    await File.WriteAllTextAsync(paths.ScheduleStateFile, "{broken");
    await Throws<System.Text.Json.JsonException>(() => Task.Run(() => stateStore.TryClaim(occurrence.AddDays(14))));
    Console.WriteLine("All smoke checks passed.");
    if (args.Length == 3 && args[0] == "--prepare-steam-candidate")
    {
        var inputPath = Path.GetFullPath(args[1]);
        var outputPath = Path.GetFullPath(args[2]);
        if (File.Exists(outputPath) || string.Equals(inputPath, outputPath, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Тестовая копия не должна заменять существующий файл.");
        var candidate = SteamScheduledUpdatePreparation.PrepareCandidate(await File.ReadAllTextAsync(inputPath));
        await File.WriteAllTextAsync(outputPath, candidate, new System.Text.UTF8Encoding(false));
        Console.WriteLine("Prepared separate offline candidate: " + outputPath);
    }
}
finally { if (Directory.Exists(root)) Directory.Delete(root, true); }
static void Check(bool ok, string name) { if (!ok) throw new Exception(name); Console.WriteLine("PASS " + name); }
static async Task Throws<T>(Func<Task> action) where T : Exception
{
    try { await action(); } catch (T) { Console.WriteLine("PASS expected " + typeof(T).Name); return; }
    throw new Exception("Expected " + typeof(T).Name);
}
